### PR TITLE
Fix sample means

### LINKED ISSUE #105: Difference of means not calculated correctly
It looks like the simulation is not plotting the difference of means for a two-sample test, rather the mean itself. I must have failed to commit this change, this should be a relatively quick fix!

Screen Shot 2021-07-06 at 12 57 43 PM

### PR DESCRIPTION
**Pull request by DavidGmidd**
closes #105

### CODE REVIEW

**Review by ethansaxenian — CHANGES_REQUESTED** [review]
I think this needs to be structured a bit differently. Notice how the `sampleMeans` state is an array of _objects_, with `testStatistic`, `mean`, and `reject` properties - these are important!

What I would do here is either:
1. Add a new property for the difference of means and plot this value when the test is a two-sample test (a bit more involved)
2. set the `mean` property to be the difference of means during a two-sample test (much easier)

**Comment by DavidGmidd** [comment]
1. What were you referring to when you said to plot it? Does it not plot sampleMeans already?
2. This is done. Let me know what you think. @ethansaxenian

**Comment by ethansaxenian** [comment]
>What were you referring to when you said to plot it? Does it not plot sampleMeans already?

So on the graph, the x-value for each point is the `mean` property of the object

File: src/components/HypothesisTesting/SimulateTypeOneError.js [hunk 1]
```diff
@@ -68,6 +68,7 @@ export default function SimulateTypeOneError({ popShape, mu0, alpha, distType, s
         const sample2 = (testType === "twoSample") ? _.sampleSize(population2, size) : [];
         const sampleMean2 = populationMean(sample2);
         const testStatistic = (testType === "oneSample")
+        const meansDiff = 0
```
Comment (ethansaxenian) [inline src/components/HypothesisTesting/SimulateTypeOneError.js:71]: Watch out, this is now in the middle of a ternary expression that calculates `testStatistic`.

Actually, we shouldn't even need this expression anymore, I believe.

File: src/components/HypothesisTesting/SimulateTypeOneError.js [hunk 2]
```diff
@@ -87,12 +88,13 @@ export default function SimulateTypeOneError({ popShape, mu0, alpha, distType, s
 
         const sampleObject = {
           testStatistic: _.round(testStatistic, 2),
-          mean: _.round(sampleMean, 2),
+          meansDiff: _.round(sampleMean2 - sampleMean, 2),
+          mean: testType === "oneSample" ? _.round(sampleMean, 2) : meansDiff,
```
Comment (ethansaxenian) [inline src/components/HypothesisTesting/SimulateTypeOneError.js:92]: You could even combine lines 91 and 92: `mean: testType === "oneSample" ? _.round(sampleMean, 2) : _.round(sampleMean2 - sampleMean, 2)` since we're not using the `meansDiff` property anywhere.

Comment (ethansaxenian) [reply src/components/HypothesisTesting/SimulateTypeOneError.js:92]: Also, I believe this should be `sampleMean - sampleMean2`

**Review by ethansaxenian — CHANGES_REQUESTED** [review]

File: src/components/HypothesisTesting/SimulateTypeOneError.js [hunk 3]
```diff
@@ -128,6 +128,7 @@ export default function SimulateTypeOneError({ popShape, mu0, alpha, distType, s
         <Col>
           {!standardized ? (
             <NormalCurve
+              meansDiff = {sampleMeans.mean}
```
Comment (ethansaxenian) [inline src/components/HypothesisTesting/SimulateTypeOneError.js:131]: Why are we now passing this property?

File: src/components/HypothesisTesting/NormalCurve.js [hunk 4]
```diff
@@ -64,7 +64,7 @@ export default function NormalCurve({ means, mu0, popStandardDev, sampleSize, di
     means.forEach(({ testStatistic, mean, reject }) => {
       meanCounts[mean] = _.defaultTo(meanCounts[mean] + 1, 1);
       const meanObject = {
-        x: mean,
+        x: testType === "oneSample" ? mean : meansDiff,
```
Comment (ethansaxenian) [inline src/components/HypothesisTesting/NormalCurve.js:67]: Note that the `mean` attribute already holds the difference of means for a two-sample test. We don't need to pass an additional prop here.

**Review by ethansaxenian — CHANGES_REQUESTED** [review]

**Review by ethansaxenian — APPROVED** [review]
Looks good - and only needed to change 1 line!
